baseurl: "/blog"

title: MiniBlog
author: fireattack

# social links
twitter_username: ikenaikoto
github_username:  fireattack
rss: rss

show_excerpts: true # set to true to show excerpts on the homepage

#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag